name: Deploy Rust App to Azure VM

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build Binary
        run: cargo build --release

      - name: Copy Binary to VM
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VM_IP }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "target/release/rust-simple-web"
          target: "/home/${{ secrets.VM_USER }}/"

      - name: Deploy Binary
        uses: appleboy/ssh-action@master
        with:
         host: ${{ secrets.VM_IP }}
         username: ${{ secrets.VM_USER }}
         key: ${{ secrets.SSH_PRIVATE_KEY }}
         script: |
             mkdir -p /home/${{ secrets.VM_USER }}/target/release
             mv -f /home/${{ secrets.VM_USER }}/target/release/rust-simple-web /home/${{ secrets.VM_USER }}/rust-simple-web/target/release/rust-simple-web
             chmod +x /home/${{ secrets.VM_USER }}/rust-simple-web/target/release/rust-simple-web
             sudo systemctl restart rust-simple-web



            

